version: '3.4'

services:

  users-service:
    container_name: users-service
    build:
      context: ./users-service
      dockerfile: Dockerfile-dev
    volumes:
       - './users-service:/usr/src/app'
    environment:
       - FLASK_APP=project/__init__.py
       - FLASK_DEBUG=1
    ports:
       - 5001:5000